version: '3.8'

services:
  postgres:
    image: postgres:15 # Versão
    container_name: postgres_db
    ports:
      - "5433:5432"    # Expõe a porta 5432 do container para a porta 5432 da sua máquina
    environment:
      POSTGRES_USER: root      # Usuário padrão
      POSTGRES_PASSWORD: root   # Senha padrão
      POSTGRES_DB: spring-security   # Nome do banco de dados inicial
    volumes:
      - pgdata:/var/lib/postgresql/data  # Volume persistente para os dados do DB
    restart: unless-stopped

volumes:
  pgdata: